package Pantalla;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luuxc
 */
public class Pantalla extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla.class.getName());

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelTiutulo = new javax.swing.JLabel();
        jLabel2Titulo = new javax.swing.JLabel();
        entradaTextField = new javax.swing.JTextField();
        celsiusRB = new javax.swing.JRadioButton();
        farenheitRB = new javax.swing.JRadioButton();
        radianesRB = new javax.swing.JRadioButton();
        kelvinRB = new javax.swing.JRadioButton();
        BTNconvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTiutulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTiutulo.setText("conversor de temperatura");

        jLabel2Titulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2Titulo.setText("ingrese temperatura en grados:");

        entradaTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        entradaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buttonGroup1.add(celsiusRB);
        celsiusRB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        celsiusRB.setText("A Celsius");

        buttonGroup1.add(farenheitRB);
        farenheitRB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        farenheitRB.setText("A Farenheit");

        buttonGroup1.add(radianesRB);
        radianesRB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radianesRB.setText("A Radianes");

        buttonGroup1.add(kelvinRB);
        kelvinRB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        kelvinRB.setText("A Kelvin");

        BTNconvertir.setText("CONVERTIR");
        BTNconvertir.addActionListener(this::BTNconvertirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTiutulo)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2Titulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(entradaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kelvinRB)
                            .addComponent(farenheitRB))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radianesRB)
                            .addComponent(celsiusRB)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(BTNconvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelTiutulo)
                .addGap(40, 40, 40)
                .addComponent(jLabel2Titulo)
                .addGap(18, 18, 18)
                .addComponent(entradaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celsiusRB)
                    .addComponent(farenheitRB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radianesRB)
                    .addComponent(kelvinRB))
                .addGap(18, 18, 18)
                .addComponent(BTNconvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNconvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNconvertirActionPerformed
        // TODO add your handling code here:
        try {
        // Leemos el texto ingresado y lo convertimos a número
        double celsius = Double.parseDouble(entradaTextField.getText());
        double resultado;
        String mensaje;

        // Verificamos qué opción seleccionó el usuario
        if (farenheitRB.isSelected()) {
            resultado = celsius * 9.0 / 5.0 + 32;
            mensaje = "La temperatura en grados fahrenheit es: " + String.format("%.1f", resultado);
        } else if (celsiusRB.isSelected()) {
            resultado = celsius;
            mensaje = "La temperatura en grados celsius es: " + resultado;
        } else if (kelvinRB.isSelected()) {
            resultado = celsius + 273.15;
            mensaje = "La temperatura en Kelvin es: " + String.format("%.2f", resultado);
        } else if (radianesRB.isSelected()) {
            resultado = celsius * (Math.PI / 180.0);
            mensaje = "El valor en radianes es: " + String.format("%.4f", resultado);
        } else {
            // En caso de que no haya seleccionado ninguno
            JOptionPane.showMessageDialog(this, "Por favor seleccione una opción de conversión.");
            return; // Se detiene solo si no marcó ninguno
        }

        // Muestra la ventana con el resultado final
        JOptionPane.showMessageDialog(this, mensaje);

    } catch (NumberFormatException e) {
        // Muestra mensaje si ingresó letras o dejó el campo vacío
        JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BTNconvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pantalla().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNconvertir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton celsiusRB;
    private javax.swing.JTextField entradaTextField;
    private javax.swing.JRadioButton farenheitRB;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2Titulo;
    private javax.swing.JLabel jLabelTiutulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton kelvinRB;
    private javax.swing.JRadioButton radianesRB;
    // End of variables declaration//GEN-END:variables
}
